"""empty message

Revision ID: abe2ffad59aa
Revises: a9ebe5c71f12
Create Date: 2024-09-05 12:06:58.632041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe2ffad59aa'
down_revision = 'a9ebe5c71f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waphone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('waphone')

    # ### end Alembic commands ###
